server:
  port: 5030

spring:
    application:
      name: order-server
    datasource:
      username: root
      password: root
      url: jdbc:mysql://47.100.202.83:3306/mall_oms?useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
    cloud:
      nacos:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto